spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.zazaero_copy
    url: jdbc:mysql://127.0.0.1:3306/db/zazaero_copy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: WENDY_739597
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MYSQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    issuer: woody@zzro.kr
    secret_key: zzro-backend