spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zazaero?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: WENDY_739597
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    url: jdbc:h2:mem:testdb
    username: sa

  jwt:
    issuer: woody@zzro.kr
    secret_key: 502f942171f059248777552cfe97dfbb75fb25d54b0d933e3d9337051eea9a3c